# Generated by Django 5.1.3 on 2026-01-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='precio',
            new_name='monto',
        ),
    ]
