# Generated by Django 5.1.3 on 2026-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_rename_precio_ingreso_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='M', max_length=1, null=True),
        ),
    ]
