# Generated by Django 5.1.3 on 2026-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_ingreso_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
