# Generated by Django 4.2 on 2025-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idaccess', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=500)),
                ('fechanacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default='M', max_length=1)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('numerodocumento', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=500, null=True)),
                ('correoelectronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('obrasocial', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
                ('proximoturno', models.CharField(blank=True, max_length=500, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('aviso', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
