# Generated by Django 4.2 on 2025-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
