# Generated by Django 5.1.3 on 2025-12-05 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosmiatras', '0002_cosmetologa'),
        ('tratamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('modo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('TC', 'Tarjeta de crédito'), ('OT', 'Otro')], max_length=2)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(max_length=500)),
                ('cosmetologa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='cosmiatras.cosmetologa')),
                ('tratamientos', models.ManyToManyField(related_name='turnos', to='tratamientos.tratamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
