# Generated by Django 5.1.3 on 2025-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
