# Generated by Django 5.1.3 on 2025-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
