# Generated by Django 5.1.3 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
