# Generated by Django 5.1.3 on 2025-12-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historialproducto'),
        ('turnos', '0004_turno_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='productos',
            field=models.ManyToManyField(related_name='consumos', to='productos.producto'),
        ),
    ]
