# Generated by Django 5.1.3 on 2025-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historialproducto'),
        ('turnos', '0005_turno_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='consumos', to='productos.producto'),
        ),
    ]
