# Generated by Django 5.1.3 on 2025-12-17 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_historialproducto_observaciones_and_more'),
        ('turnos', '0006_alter_turno_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad Consumida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
            options={
                'unique_together': {('turno', 'producto')},
            },
        ),
    ]
