# Generated by Django 5.1.3 on 2026-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_turnoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='nombrepaciente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='numerodocumento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
