# Generated by Django 5.1.3 on 2026-01-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_turno_nombrepaciente_turno_numerodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default='M', max_length=1),
        ),
    ]
