# Generated by Django 5.1.3 on 2025-12-09 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('precio_registrado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_registrado', models.IntegerField()),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('EDITADO', 'Editado')], max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='productos.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Producto',
                'verbose_name_plural': 'Historial de Productos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
