# Generated by Django 5.1.3 on 2025-12-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historialproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproducto',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('EDITADO', 'Editado'), ('TURNO', 'Turno')], max_length=10),
        ),
    ]
