# Generated by Django 5.1.3 on 2025-12-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_historialproducto_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproducto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('EDITADO', 'Editado'), ('TURNO', 'Turno')], max_length=20),
        ),
    ]
