# Generated by Django 5.1.3 on 2025-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_historialproducto_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproducto',
            name='stock_registrado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
