# Generated by Django 4.2 on 2025-12-01 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_alter_paciente_fechanacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idaccess', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('historia', models.CharField(blank=True, max_length=1000, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=1000, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=1000, null=True)),
                ('primeravez', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historias Clinicas',
            },
        ),
    ]
