# Generated by Django 4.2 on 2025-12-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiasclinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historias_clinicas/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaclinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='historiasclinicas.historiaclinica')),
            ],
        ),
    ]
