# Generated by Django 4.2 on 2025-12-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiasclinicas', '0002_imagenhistoriaclinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenhistoriaclinica',
            name='descripcion',
        ),
    ]
